repos:
  # Versioning: Commit Messages & Changelog
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.27.1
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Autoformat: YAML, JSON, Markdown, etc.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.1
    hooks:
      - id: prettier
        args:
          [
            "--ignore-unknown",
            "--no-error-on-unmatched-pattern",
            "!chart/**",
            "--ignore-path",
            ".dockerignore",
          ]

  # Lint: Dockerfile
  - repo: https://github.com/hadolint/hadolint.git
    rev: v2.10.0
    hooks:
      - id: hadolint-docker
        entry: hadolint/hadolint:v2.8.0 hadolint
        args: ["--ignore=DL3008", "--ignore=DL3013", "--ignore=DL3018"]

  # Lint: YAML
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        args:
          [
            "-d {extends: relaxed, rules: {line-length: disable}, ignore: chart}",
            "-s",
          ]
        files: \.(yaml|yml)$

  # Lint: Bash scripts
  - repo: https://github.com/openstack-dev/bashate.git
    rev: 2.1.0
    hooks:
      - id: bashate
        args: ["--ignore=E006,E010"]

  # Lint: Javascript
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.17.0
    hooks:
      - id: eslint
        args: ["--ext", ".js,.ts,.vue"]

  # Lint: Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
        args: ["--fix", "--disable", "MD024"]
